type PantryItem @model @auth(rules: [{ allow: private }]) {
  id: ID!
  name: String!
  category: String
  quantity: Int
  lastUpdated: AWSDateTime
  restockRequests: [RestockRequest] @connection(keyName: "byItem", fields: ["id"])
  consumptionLogs: [ConsumptionLog] @connection(keyName: "byItem", fields: ["id"])
}

type RestockRequest
  @model
  @auth(rules: [{ allow: private }])
  @key(name: "byItem", fields: ["itemID"]) {
  id: ID!
  itemID: ID!
  item: PantryItem @connection(fields: ["itemID"])
  requestedBy: String
  quantity: Int
  status: String
  createdAt: AWSDateTime
}

type ConsumptionLog
  @model
  @auth(rules: [{ allow: private }])
  @key(name: "byItem", fields: ["itemID"]) {
  id: ID!
  itemID: ID!
  item: PantryItem @connection(fields: ["itemID"])
  consumedBy: String
  amount: Int
  date: AWSDateTime
}
